### ISSUE TITLE
Adding more CloudLaunch CLI documentation 

### ISSUE THREAD

**Issue by bioboot** [CloudVE/cloudlaunch-cli#20]
* CloudLaunch CLI obtained from following QuickStart/README.md
* Python 3.8.5
* macOS Catalina 10.15.7

### Description
I get errors using `cloudlaunch deployments create` and can't find docs to help me out (see below).

### Background
I love the ease and utility of using CloudLaunch through the web interface and would like to learn more about using the CLI. The quick start guide worked as advertised and I can list my deployments with 

```
cloudlaunch deployments list
```

and I see there is a `create` option but I don't see any documentation for that beyond what I can get with the `--help` flag.

```
cloudlaunch deployments create [OPTIONS] NAME APPLICATION CLOUD
```

Trying the cmd from the quickstart page and the README.md here yields an error for me (see below). I guess I am missing some "required parameters" like `id` and I have tried a few variants but would benefit from some documentation and/or guidance. Thanks!

```
> cloudlaunch deployments create my-ubuntu-test ubuntu amazon-us-east-n-virginia --application-version 16.04
Traceback (most recent call last):
  File "/Users/barry/tmpwork/gvl-cmdlaunch/venv/bin/cloudlaunch", line 8, in <module>
    sys.exit(client())
  File "/Users/barry/tmpwork/gvl-cmdlaunch/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/barry/tmpwork/gvl-cmdlaunch/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/barry/tmpwork/gvl-cmdlaunch/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/barry/tmpwork/gvl-cmdlaunch/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/barry/tmpwork/gvl-cmdlaunch/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/barry/tmpwork/gvl-cmdlaunch/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/barry/tmpwork/gvl-cmdlaunch/venv/lib/python3.8/site-packages/cloudlaunch_cli/main.py", line 103, in create_deployment
    cloudlaunch_client = create_api_client(cloud)
  File "/Users/barry/tmpwork/gvl-cmdlaunch/venv/lib/python3.8/site-packages/cloudlaunch_cli/main.py", line 20, in create_api_client
    cloud_resource = cloudlaunch_client.infrastructure.clouds.get(cloud)
  File "/Users/barry/tmpwork/gvl-cmdlaunch/venv/lib/python3.8/site-packages/cloudlaunch_cli/api/endpoints.py", line 96, in get
    item = self._client.action(document, self.path + ['read'],
  File "/Users/barry/tmpwork/gvl-cmdlaunch/venv/lib/python3.8/site-packages/coreapi/client.py", line 160, in action
    _validate_parameters(link, params)
  File "/Users/barry/tmpwork/gvl-cmdlaunch/venv/lib/python3.8/site-packages/coreapi/client.py", line 80, in _validate_parameters
    raise exceptions.ParameterError(errors)
coreapi.exceptions.ParameterError: {'id': 'This parameter is required.', 'slug': 'Unknown parameter.'}
```

**Comment by nuwang** [comment]
@bioboot At present, the documentation is virtually non-existent. Possibly the best point of reference are the tests:
https://github.com/CloudVE/cloudlaunch-cli/blob/7641361c93610b29ae8aea180ebe48b64a5a7dac/tests/test_cloudlaunch_cli.py#L56

We've been intending to switch the cli from coreapi to openapi, and have the cli auto-generated, so that the documentation and examples also become clearer, but due to time pressure, that has gone into the backburner. PRs and doc updates would be most welcome.
