### ISSUE TITLE
Unable to list deployments

### ISSUE THREAD

**Issue by nuwang** [CloudVE/cloudlaunch-cli#6]
* Python version: 3.6.2
* Operating System: OsX

### Description

Trying to list deployments using the cli client results in an exception.

### What I Did

```
(cloudlaunch-cli)Nuwan@Nuwans-MBP-2 cloudlaunch_cli (master)$ cloudlaunch deployments list
Traceback (most recent call last):
  File "/Users/Nuwan/work/cloudlaunch-cli/venv/bin/cloudlaunch", line 11, in <module>
    load_entry_point('cloudlaunch-cli', 'console_scripts', 'cloudlaunch')()
  File "/Users/Nuwan/work/cloudlaunch-cli/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Nuwan/work/cloudlaunch-cli/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/Nuwan/work/cloudlaunch-cli/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Nuwan/work/cloudlaunch-cli/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Nuwan/work/cloudlaunch-cli/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Nuwan/work/cloudlaunch-cli/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/Nuwan/work/cloudlaunch-cli/cloudlaunch_cli/main.py", line 80, in list_deployments
    deployments = cloudlaunch_client.deployments.list(archived=archived)
  File "/Users/Nuwan/work/cloudlaunch-cli/cloudlaunch_cli/api/endpoints.py", line 100, in list
    return [self._create_response(item) for item in items['results']]
TypeError: string indices must be integer
```

**Comment by nuwang** [comment]
@machristie I think I found the problem. The schema  is listing endpoints incorrectly: https://launch.usegalaxy.org/cloudlaunch/api/v1/schema/

**Comment by machristie** [comment]
That's odd because it works for me. I wonder if this is due to the authentication issue. Did you configure your API token?
